name: flutteractual
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  flutter_secure_storage: ^6.0.0
  json_annotation: ^4.7.0
  retrofit: '>=3.0.0 <4.0.0'
  logger: any

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.0.0
  json_serializable: ^6.0.0
  retrofit_generator: '>=4.0.0 <5.0.0'

flutter:

  uses-material-design: true
  assets:
    - assets/img/food/
    - assets/img/logo/
    - assets/img/misc/
    - assets/rive/
    - assets/svg/icon/
    - assets/foods.json
    - assets/food_detail.json

  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSansKR-Black.otf
          weight: 900
        - asset: assets/fonts/NotoSansKR-Bold.otf
          weight: 700
        - asset: assets/fonts/NotoSansKR-Light.otf
          weight: 500
        - asset: assets/fonts/NotoSansKR-Medium.otf
          weight: 400
        - asset: assets/fonts/NotoSansKR-Regular.otf
          weight: 300
        - asset: assets/fonts/NotoSansKR-Thin.otf
          weight: 100

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
